
modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"

[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}.mixins-forge.json"

[[mods]]
    modId = "polytone"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile = "icon.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
    modUrl = "${mod_homepage}"
    itemIcon="minecraft:brush" #catalogue icon

[[dependencies.polytone]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.polytone]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_min_version},${minecraft_max_version})"
    ordering = "NONE"
    side = "CLIENT"


